//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billiard
{
    using System;
    using System.Collections.Generic;
    
    public partial class pooltable
    {
        public int id_table { get; set; }
        public string num_table { get; set; }
        public string booking { get; set; }
    }
}
