//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billiard
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitors
    {
        public int id_visitor { get; set; }
        public string fio { get; set; }
        public string parties { get; set; }
        public string card_status { get; set; }
        public int visit_price { get; set; }
    }
}
